language: objective-c
xcode_workspace: testApp/testApp.xcworkspace
xcode_scheme: testApp
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
before_install:
- brew update
- brew outdated homebrew/versions/node4-lts || brew install homebrew/versions/node4-lts
- gem update fastlane
# Force bundler 1.12.5 because version 1.13 has issues, see https://github.com/fastlane/fastlane/issues/6065#issuecomment-246044617
- gem uninstall bundler -v '>1.12.5' --force || echo "bundler >1.12.5 is not installed"
- gem install bundler -v 1.12.5 --no-rdoc --no-ri --no-document --quiet
env:
    global:
        secure: "dfXpDj2Q/9QhoJ3T/Ho1B+4dUG9wKxFbWQEX28lhI7M/FRh3lB/lLwJ1zP6q5Z1/r+SQZ6SCExTjCtbPhTmMKAUPh8fTBE7DZuBmvbc0Qwh4FBuMDbS8vV2vmzSvP15+OF6GBci4/HTfAwU0GhYYw28nKQ+OLsyyYfjdhOEs80lYbACrG8/MfEy92pR2hwA2TzZF2nOhxGm33YjM8hl48l934mXwPCCM7LHY+cDnY4q2FdxvNqFNSwuwMBHwiDsSeS4kj1t3VHef4ynrOF3cyXEde9Qq8xw/5KeJkASJOF2xi/CyEu5E37TfiTs7XQgb9o/MQJtHJYUKwjkHDSfd468yEX3BQHhw2TJF8q4tEMTOrN8gZxYGVGkLY6dm6kh0BonV3Th62Ns5VFmMNoP+IG8TpjVpnj/VONdGrfsNlndjYYfEdXUiPvn5Ws4tzEfuhwzd9e5Sh72JTvrVBJA4nQtpkXuot2kYtEiiMVnvyRZkdoheX/ak6dem35shpzdZTQR6SgwqjkUaJEA8HFdCgXMIL4a70Ui2qAu0FX1Ed96RWFTpgXEP6iLkJ8H0ynUC4hABYn1c1uuFSKVSBP7Wf4RSNaVLLhQxycdcSjZCVNJS5lPGDwir7XwKfQS3XWaojY1mYzI87kZMhdPsKw88RONq5WVGQkl4l/enOwxFRpA="

script:
- cd testApp/ && ./fastlane/travis.sh
