language: objective-c
xcode_workspace: testApp/testApp.xcworkspace
xcode_scheme: testApp
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
env:
- TESTVAR2=abcqqq
before_install:
- openssl aes-256-cbc -K $encrypted_4cc2ae6d66f3_key -iv $encrypted_4cc2ae6d66f3_iv
  -in ./testApp/fastlane/apple_credentials.sh.enc -out ./testApp/fastlane/apple_credentials.sh -d
- brew update
- brew outdated homebrew/versions/node4-lts || brew install homebrew/versions/node4-lts
- gem update fastlane
- gem uninstall bundler -v '>1.12.5' --force || echo "bundler >1.12.5 is not installed"
- gem install bundler -v 1.12.5 --no-rdoc --no-ri --no-document --quiet
script:
- cd testApp/ && ./fastlane/apple_credentials.sh && ./fastlane/travis.sh
