language: objective-c
xcode_workspace: testApp/testApp.xcworkspace
xcode_scheme: testApp
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
env:
- TESTVAR2=abcqqq
  global:
  - TESTVAR=abc
  - secure: PBjzCJMm8QFXwlmEf4VoEKlhXXzO8XnavpWKDskk9dcKPvTm86BBcV3icjGAzkKSUiO+P9y0QvwJeBrdlZwUr4qL9Lezx5ldpcOimEUWPGL/Y5FX7f4eawKNCDn5lRkdoNYoa7Vb3hZy52sSAM6f0RZ5FkliXxqTMLH15EazaMaP2H4+nkZ97m7cV67l1evkJCIEwyOqtMiLRM0k/Y6vn/PfhDYoh7WD0a8IY4sAyNaUOz0fwaO7NxXMzXxYALuYzMf/ZUJsRwtIhCozyHinX6v0moA5u1Vjx7wS3vNzTAgQRbSWcatmbOGnPsUHYY/MGMbBPoUlWAsX+7sF0i2NRZ0cS5JRjkLVeic+pf+2sRq86uRGOZCzJPvFRGcmNmI7sKMd8coViKDUR1yK4/PMxp/Cc8ZatQjbzEEwoElRC8UUAdahg8dCulHJSE8AYNn2UzLMnl/bM3b4MRr+ZrrX+ONiCxKTHZB7Iuj/VkpnISmDsWxRZSp33E57NDTI28b5miVVOtRIWXbe68/mqla9FH6vRVmmGwb3qYaILZt74z7itwhN2X+8Yvk3tSGmrfeT7107wl79+r+KfYH+PFXOcNdh94d1tK+xwZPq4vHOXM50h2GKbD+DkrxyoGZ+7ubrFGnJZ2aRnpFKkzX9OkPaWD8KAX4s0Ls06k4quI9tH20=
before_install:
- brew update
- brew outdated homebrew/versions/node4-lts || brew install homebrew/versions/node4-lts
- gem update fastlane
- gem uninstall bundler -v '>1.12.5' --force || echo "bundler >1.12.5 is not installed"
- gem install bundler -v 1.12.5 --no-rdoc --no-ri --no-document --quiet
script:
- cd testApp/ && ./fastlane/travis.sh
