language: objective-c
xcode_workspace: testApp/testApp.xcworkspace
xcode_scheme: testApp
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
before_install:
- brew update
- brew outdated homebrew/versions/node4-lts || brew install homebrew/versions/node4-lts
- gem update fastlane
# Force bundler 1.12.5 because version 1.13 has issues, see https://github.com/fastlane/fastlane/issues/6065#issuecomment-246044617
- gem uninstall bundler -v '>1.12.5' --force || echo "bundler >1.12.5 is not installed"
- gem install bundler -v 1.12.5 --no-rdoc --no-ri --no-document --quiet
env:
    global:
        secure: "T+pFfMZyjoYRVqPR2j0DMS+1sqfUxz092o+Cff26Fdk7wBX+8MPi4IGGBgm/Lgo5raYE4g4S6c0Zw5p1ved5Leh4GGeAW8hgl+Dwk/TwzN74iO2TCIxRWR01eE7W+ZZEj+Tc9iBTGZHWxm6yAvzkzOQ5kcDGPZ2zKkJhowma7VIyyAfK/hegXVoF+2NElNXO3Z5h4iih4sEIVCoSMAbgl8UDQO0bMPXRAGFIS3YXE/sb2Z5su6sHlYotkiOnNcY3UskQw2jatZ9TBEBavq3YNKJ56+8AGY2DCCaOpVRvq5VdUP/LcrjRMzXhe6D0XU8sIpx9DtmSlhvx1eVWx2ZntOCzsRdGSIjqbACzgssrRZziHdD3bl0KaLMgDOpq9UmENiBrhqNZBVrkcm/pgPKf1Hoh3Mnwz30aHbrQU4QonCg+5OPXT+bMMNxSpWqGwBNL9lrYCjCaHWMaoeDDaAaGSJ3W0znUoFOLJD987lqImrTPiT+/Zy4KCv4vyleEQwOPSS3uXStQsTwlC9HMFC0ueQ1qW+9K4G+QrCihT69bVPB8lBv2cAR1G7EUHGkpMWLqFLa7cSPEvzJFC8oFYbHmsE+sZW8ojoZDLJbGstt5I7Ki0APYwcVU90gl4vD86T/QG1Cixo+YmdbvKYnuVXEzV9AxbE8HSoOyS/p5ZdatccE="

script:
- cd testApp/ && ./fastlane/travis.sh
