language: objective-c
xcode_workspace: testApp/testApp.xcworkspace
xcode_scheme: testApp
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
before_install:
- brew update
- brew outdated homebrew/versions/node4-lts || brew install homebrew/versions/node4-lts
- pod repo update --silent
- gem update fastlane
script:
- cd testApp/ && ./fastlane/travis.sh
