language: objective-c
xcode_workspace: testApp/testApp.xcworkspace # path to your xcodeproj folder
xcode_scheme: testApp
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
script:
- cd testApp/ && ./fastlane/travis.sh