# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'testApp' do

  # Just a test
  pod 'AFNetworking'

  # Pods for testApp

  target 'testAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
